/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cien_adventistas_dijeron;

import com.sun.awt.AWTUtilities;
import java.awt.Color;


import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author oñas-system
 */
public class INTERFAZ_JUEGO extends javax.swing.JFrame {
int x,y;
    /**
     * Creates new form INTERFAZ_JUEGO
     */
    public INTERFAZ_JUEGO() {
        initComponents();
        fondocolor();
     //   cargarvalores();
     // cargarpanel();
    }
      
       public static void cargarpanel(JFrame paly){
        salida.setSize(400, 400);
        salida.setLocationRelativeTo(paly);
        salida.setAlwaysOnTop(true);
       salida.setUndecorated(true);
        AWTUtilities.setWindowOpaque(salida, false);
         INTERFAZ_JUEGO.salida.setVisible(true);
        }
        public Image logotipo(){
        Image refValue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.png"));
        return refValue;
    }
void fondocolor(){
 this.getContentPane().setBackground(Color.BLACK);
        //Color JPanel
      //  jPanel1.setBackground(Color.BLACK);
jPanel3.setBackground(Color.BLACK);
jPanel4.setBackground(Color.BLACK);
jPanel5.setBackground(Color.BLACK);
jPanel6.setBackground(Color.BLACK);
panelver1.setBackground(Color.BLACK);
panelver2.setBackground(Color.BLACK);
panelver3.setBackground(Color.BLACK);
panelver4.setBackground(Color.BLACK);
panelver5.setBackground(Color.BLACK);
panelver6.setBackground(Color.BLACK);
panelver8.setBackground(Color.BLACK);
panelver10.setBackground(Color.BLACK);

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salida = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        informacionpuntos = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelver1 = new javax.swing.JPanel();
        numeral1 = new javax.swing.JLabel();
        literal1 = new javax.swing.JLabel();
        puntage1 = new javax.swing.JLabel();
        panelver2 = new javax.swing.JPanel();
        numeral2 = new javax.swing.JLabel();
        literal2 = new javax.swing.JLabel();
        puntage2 = new javax.swing.JLabel();
        panelver3 = new javax.swing.JPanel();
        numeral3 = new javax.swing.JLabel();
        literal3 = new javax.swing.JLabel();
        puntage3 = new javax.swing.JLabel();
        panelver4 = new javax.swing.JPanel();
        numeral4 = new javax.swing.JLabel();
        literal4 = new javax.swing.JLabel();
        puntage4 = new javax.swing.JLabel();
        panelver5 = new javax.swing.JPanel();
        numeral5 = new javax.swing.JLabel();
        literal5 = new javax.swing.JLabel();
        puntage5 = new javax.swing.JLabel();
        panelver6 = new javax.swing.JPanel();
        numeral6 = new javax.swing.JLabel();
        literal6 = new javax.swing.JLabel();
        puntage6 = new javax.swing.JLabel();
        panelver8 = new javax.swing.JPanel();
        numeral8 = new javax.swing.JLabel();
        literal8 = new javax.swing.JLabel();
        puntage8 = new javax.swing.JLabel();
        panelver10 = new javax.swing.JPanel();
        literal10 = new javax.swing.JLabel();
        puntage10 = new javax.swing.JLabel();
        numeral10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        preguntasalida = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        nombre1 = new javax.swing.JLabel();
        icono1_3 = new javax.swing.JLabel();
        icono1_1 = new javax.swing.JLabel();
        icono1_2 = new javax.swing.JLabel();
        puntagetotal1 = new javax.swing.JLabel();
        ronda = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        nombre2 = new javax.swing.JLabel();
        icono2_3 = new javax.swing.JLabel();
        icono2_1 = new javax.swing.JLabel();
        icono2_2 = new javax.swing.JLabel();
        puntagetotal2 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        titulo = new javax.swing.JLabel();

        salida.setAlwaysOnTop(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo JA 2015.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        informacionpuntos.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        informacionpuntos.setForeground(new java.awt.Color(51, 255, 0));
        informacionpuntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout salidaLayout = new javax.swing.GroupLayout(salida.getContentPane());
        salida.getContentPane().setLayout(salidaLayout);
        salidaLayout.setHorizontalGroup(
            salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
            .addComponent(informacionpuntos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        salidaLayout.setVerticalGroup(
            salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salidaLayout.createSequentialGroup()
                .addComponent(informacionpuntos, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("JUGUEMOS");
        setIconImage(logotipo());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelver1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        numeral1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        numeral1.setForeground(new java.awt.Color(51, 255, 0));
        numeral1.setText("1.");

        literal1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        literal1.setForeground(new java.awt.Color(51, 255, 0));
        literal1.setText("OPCION");

        puntage1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        puntage1.setForeground(new java.awt.Color(51, 255, 0));
        puntage1.setText("PUNTAJE");
        puntage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout panelver1Layout = new javax.swing.GroupLayout(panelver1);
        panelver1.setLayout(panelver1Layout);
        panelver1Layout.setHorizontalGroup(
            panelver1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numeral1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(literal1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puntage1)
                .addContainerGap())
        );
        panelver1Layout.setVerticalGroup(
            panelver1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelver1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeral1)
                    .addComponent(literal1)
                    .addComponent(puntage1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelver2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        numeral2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        numeral2.setForeground(new java.awt.Color(51, 255, 0));
        numeral2.setText("2.");

        literal2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        literal2.setForeground(new java.awt.Color(51, 255, 0));
        literal2.setText("OPCION");

        puntage2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        puntage2.setForeground(new java.awt.Color(51, 255, 0));
        puntage2.setText("PUNTAJE");
        puntage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout panelver2Layout = new javax.swing.GroupLayout(panelver2);
        panelver2.setLayout(panelver2Layout);
        panelver2Layout.setHorizontalGroup(
            panelver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numeral2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(literal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puntage2)
                .addContainerGap())
        );
        panelver2Layout.setVerticalGroup(
            panelver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeral2)
                    .addComponent(literal2)
                    .addComponent(puntage2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelver3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        numeral3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        numeral3.setForeground(new java.awt.Color(51, 255, 0));
        numeral3.setText("3.");

        literal3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        literal3.setForeground(new java.awt.Color(51, 255, 0));
        literal3.setText("OPCION");

        puntage3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        puntage3.setForeground(new java.awt.Color(51, 255, 0));
        puntage3.setText("PUNTAJE");
        puntage3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout panelver3Layout = new javax.swing.GroupLayout(panelver3);
        panelver3.setLayout(panelver3Layout);
        panelver3Layout.setHorizontalGroup(
            panelver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numeral3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(literal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puntage3)
                .addContainerGap())
        );
        panelver3Layout.setVerticalGroup(
            panelver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeral3)
                    .addComponent(literal3)
                    .addComponent(puntage3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelver4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        numeral4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        numeral4.setForeground(new java.awt.Color(51, 255, 0));
        numeral4.setText("4.");

        literal4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        literal4.setForeground(new java.awt.Color(51, 255, 0));
        literal4.setText("OPCION");

        puntage4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        puntage4.setForeground(new java.awt.Color(51, 255, 0));
        puntage4.setText("PUNTAJE");
        puntage4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout panelver4Layout = new javax.swing.GroupLayout(panelver4);
        panelver4.setLayout(panelver4Layout);
        panelver4Layout.setHorizontalGroup(
            panelver4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numeral4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(literal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puntage4)
                .addContainerGap())
        );
        panelver4Layout.setVerticalGroup(
            panelver4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelver4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeral4)
                    .addComponent(literal4)
                    .addComponent(puntage4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelver5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        numeral5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        numeral5.setForeground(new java.awt.Color(51, 255, 0));
        numeral5.setText("5.");

        literal5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        literal5.setForeground(new java.awt.Color(51, 255, 0));
        literal5.setText("OPCION");

        puntage5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        puntage5.setForeground(new java.awt.Color(51, 255, 0));
        puntage5.setText("PUNTAJE");
        puntage5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout panelver5Layout = new javax.swing.GroupLayout(panelver5);
        panelver5.setLayout(panelver5Layout);
        panelver5Layout.setHorizontalGroup(
            panelver5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numeral5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(literal5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(puntage5)
                .addContainerGap())
        );
        panelver5Layout.setVerticalGroup(
            panelver5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelver5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeral5)
                    .addComponent(literal5)
                    .addComponent(puntage5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelver6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        numeral6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        numeral6.setForeground(new java.awt.Color(51, 255, 0));
        numeral6.setText("6.");

        literal6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        literal6.setForeground(new java.awt.Color(51, 255, 0));
        literal6.setText("OPCION");

        puntage6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        puntage6.setForeground(new java.awt.Color(51, 255, 0));
        puntage6.setText("PUNTAJE");
        puntage6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout panelver6Layout = new javax.swing.GroupLayout(panelver6);
        panelver6.setLayout(panelver6Layout);
        panelver6Layout.setHorizontalGroup(
            panelver6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelver6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numeral6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(literal6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puntage6)
                .addContainerGap())
        );
        panelver6Layout.setVerticalGroup(
            panelver6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelver6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puntage6)
                    .addGroup(panelver6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(literal6)
                        .addComponent(numeral6)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelver8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        numeral8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        numeral8.setForeground(new java.awt.Color(51, 255, 0));
        numeral8.setText("7.");

        literal8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        literal8.setForeground(new java.awt.Color(51, 255, 0));
        literal8.setText("OPCION");

        puntage8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        puntage8.setForeground(new java.awt.Color(51, 255, 0));
        puntage8.setText("PUNTAJE");
        puntage8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout panelver8Layout = new javax.swing.GroupLayout(panelver8);
        panelver8.setLayout(panelver8Layout);
        panelver8Layout.setHorizontalGroup(
            panelver8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numeral8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(literal8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puntage8)
                .addContainerGap())
        );
        panelver8Layout.setVerticalGroup(
            panelver8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelver8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeral8)
                    .addGroup(panelver8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(literal8)
                        .addComponent(puntage8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelver10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        literal10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        literal10.setForeground(new java.awt.Color(51, 255, 0));
        literal10.setText("OPCION");

        puntage10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        puntage10.setForeground(new java.awt.Color(51, 255, 0));
        puntage10.setText("PUNTAJE");
        puntage10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        numeral10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        numeral10.setForeground(new java.awt.Color(51, 255, 0));
        numeral10.setText("8.");

        javax.swing.GroupLayout panelver10Layout = new javax.swing.GroupLayout(panelver10);
        panelver10.setLayout(panelver10Layout);
        panelver10Layout.setHorizontalGroup(
            panelver10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numeral10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(literal10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(puntage10)
                .addContainerGap())
        );
        panelver10Layout.setVerticalGroup(
            panelver10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelver10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelver10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(literal10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelver10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numeral10)
                        .addComponent(puntage10)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelver1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelver2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelver3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelver4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelver5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelver6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelver8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelver10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(panelver1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelver2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelver3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelver4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelver5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelver6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelver8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelver10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setForeground(new java.awt.Color(51, 255, 0));

        preguntasalida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        preguntasalida.setForeground(new java.awt.Color(255, 204, 0));
        preguntasalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preguntasalida.setText("PRENTAS------------------------------------------------");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(preguntasalida, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(preguntasalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        nombre1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        nombre1.setForeground(new java.awt.Color(102, 102, 255));
        nombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre1.setText("Nombre");

        icono1_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_letter_X_red_1553096 - copia.png"))); // NOI18N
        icono1_3.setToolTipText("TERCER STRIK");

        icono1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_letter_X_red_1553096 - copia.png"))); // NOI18N
        icono1_1.setToolTipText("PRIMER STRIK");

        icono1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_letter_X_red_1553096 - copia.png"))); // NOI18N
        icono1_2.setToolTipText("SEGUNDO STRIK");

        puntagetotal1.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        puntagetotal1.setForeground(new java.awt.Color(255, 0, 255));
        puntagetotal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntagetotal1.setText("000");
        puntagetotal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4));

        ronda.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        ronda.setForeground(new java.awt.Color(255, 255, 0));
        ronda.setText("RONDA #");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puntagetotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(icono1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icono1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icono1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(ronda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ronda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(nombre1)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icono1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icono1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icono1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(puntagetotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nombre2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        nombre2.setForeground(new java.awt.Color(102, 102, 255));
        nombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre2.setText("Nombre");

        icono2_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_letter_X_red_1553096 - copia.png"))); // NOI18N
        icono2_3.setToolTipText("TERCER STRIK");

        icono2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_letter_X_red_1553096 - copia.png"))); // NOI18N
        icono2_1.setToolTipText("PRIMER STRIK");

        icono2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/if_letter_X_red_1553096 - copia.png"))); // NOI18N
        icono2_2.setToolTipText("SEGUNDO STRIK");

        puntagetotal2.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        puntagetotal2.setForeground(new java.awt.Color(255, 0, 255));
        puntagetotal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puntagetotal2.setText("000");
        puntagetotal2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 4));

        total.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        total.setForeground(new java.awt.Color(51, 255, 0));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("000");
        total.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 0), 3, true));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puntagetotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(nombre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(icono2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icono2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icono2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(nombre2)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icono2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icono2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icono2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(puntagetotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titulo.setFont(new java.awt.Font("Lucida Calligraphy", 1, 30)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("<html> <style type=\"text/css\"> body{text-align: center; font-weight:bold; font-family: Lucida Calligraphy;   font-size:30px;} .primer{color:#FFFFFF;} .segundo{color:#FF0000;} </style> <span class=\"primer\">100 ADVENTISTAS DIJERON</span> </html>");
        titulo.setToolTipText("pulsa para poner en pantalla completa");
        titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tituloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(titulo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseClicked
     this.setExtendedState(MAXIMIZED_BOTH); 
// TODO add your handling code here:
    }//GEN-LAST:event_tituloMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     int p=JOptionPane.showConfirmDialog(this,"Esta en modo Juego Activo\n¿Esta seguro que desea cerra esta ventana?","Cerrar modo proyeccion", JOptionPane.YES_NO_OPTION);
      if(p==JOptionPane.YES_OPTION){  
      this.hide();
        CONTROL.star.setEnabled(true);
      } // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
       x= evt.getX();
      y=evt.getY();  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
         salida.setLocation(salida.getLocation().x+evt.getX()-x,salida.getLocation().y+evt.getY()- y);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ_JUEGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ_JUEGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ_JUEGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INTERFAZ_JUEGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INTERFAZ_JUEGO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel icono1_1;
    public static javax.swing.JLabel icono1_2;
    public static javax.swing.JLabel icono1_3;
    public static javax.swing.JLabel icono2_1;
    public static javax.swing.JLabel icono2_2;
    public static javax.swing.JLabel icono2_3;
    public static javax.swing.JLabel informacionpuntos;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JLabel literal1;
    public static javax.swing.JLabel literal10;
    public static javax.swing.JLabel literal2;
    public static javax.swing.JLabel literal3;
    public static javax.swing.JLabel literal4;
    public static javax.swing.JLabel literal5;
    public static javax.swing.JLabel literal6;
    public static javax.swing.JLabel literal8;
    public static javax.swing.JLabel nombre1;
    public static javax.swing.JLabel nombre2;
    public static javax.swing.JLabel numeral1;
    public static javax.swing.JLabel numeral10;
    public static javax.swing.JLabel numeral2;
    public static javax.swing.JLabel numeral3;
    public static javax.swing.JLabel numeral4;
    public static javax.swing.JLabel numeral5;
    public static javax.swing.JLabel numeral6;
    public static javax.swing.JLabel numeral8;
    public static javax.swing.JPanel panelver1;
    public static javax.swing.JPanel panelver10;
    public static javax.swing.JPanel panelver2;
    public static javax.swing.JPanel panelver3;
    public static javax.swing.JPanel panelver4;
    public static javax.swing.JPanel panelver5;
    public static javax.swing.JPanel panelver6;
    public static javax.swing.JPanel panelver8;
    public static javax.swing.JLabel preguntasalida;
    public static javax.swing.JLabel puntage1;
    public static javax.swing.JLabel puntage10;
    public static javax.swing.JLabel puntage2;
    public static javax.swing.JLabel puntage3;
    public static javax.swing.JLabel puntage4;
    public static javax.swing.JLabel puntage5;
    public static javax.swing.JLabel puntage6;
    public static javax.swing.JLabel puntage8;
    public static javax.swing.JLabel puntagetotal1;
    public static javax.swing.JLabel puntagetotal2;
    public static javax.swing.JLabel ronda;
    public static javax.swing.JDialog salida;
    public static javax.swing.JLabel titulo;
    public static javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
